### ISSUE TITLE
decimal point in a1c calculator causes crash

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#234]
From Dev Console:

java.lang.NumberFormatException: Invalid double: ""
	at java.lang.StringToReal.invalidReal(StringToReal.java:63)
	at java.lang.StringToReal.initialParse(StringToReal.java:176)
	at java.lang.StringToReal.parseDouble(StringToReal.java:282)
	at java.lang.Double.parseDouble(Double.java:301)
	at org.glucosio.android.presenter.A1CCalculatorPresenter.calculateA1C(A1CCalculatorPresenter.java)
	                                                         checkGlucoseUnit(A1CCalculatorPresenter.java)
	                                                         saveA1C(A1CCalculatorPresenter.java)
	at org.glucosio.android.activity.A1cCalculator$1.afterTextChanged(A1cCalculator.java)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:9196)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:11940)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1047)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:564)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:494)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:34)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:691)
	at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:199)
	at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:184)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:286)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by emartynov** [comment]
@bkerensa Do you remember what you did to get crash? How to reproduce it? Would be helpful

**Comment by emartynov** [comment]
Just read properly the name of issue, which says what you entered
